Date timestamp: 2021-09-13 11:10:03.945620Traceback (most recent call last):
  File "/home/aidar/Documents/Projects/SSD_Assignment_1/src/task4.py", line 26, in wrapper
    func(*args, **kargs)
  File "main.py", line 104, in func_error
    raise Exception('Python!')
Exception: Python!
